const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const output = ts.transpileModule(fs.readFileSync('src/lib/availability.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText;
const lib = { exports: {} };
new Function('require', 'module', 'exports', output)(require, lib, lib.exports);
const { availabilitySchema, timeSlots, athensDate, athensParts, isAvailable } = lib.exports;
const slot = { dayOfWeek: 1, startTime: '09:30', endTime: '11:00' };
assert.deepEqual(timeSlots(slot.startTime, slot.endTime), ['09:30']);
assert.equal(availabilitySchema.safeParse([]).success, true);
assert.equal(availabilitySchema.safeParse([slot]).success, true);
for (const bad of [ { ...slot, dayOfWeek: 7 }, { ...slot, startTime: '25:00' }, { ...slot, endTime: '09:45' } ]) assert.equal(availabilitySchema.safeParse([bad]).success, false);
assert.equal(availabilitySchema.safeParse([slot, { ...slot, startTime: '10:00', endTime: '12:00' }]).success, false);
assert.equal(availabilitySchema.safeParse([slot, { ...slot, startTime: '11:00', endTime: '12:00' }]).success, true);
assert.equal(athensDate('2026-09-21', '09:30').toISOString(), '2026-09-21T06:30:00.000Z');
assert.equal(athensDate('2026-01-05', '09:30').toISOString(), '2026-01-05T07:30:00.000Z');
assert.equal(isAvailable(athensDate('2026-09-21', '09:30'), [slot]), true);
assert.equal(isAvailable(athensDate('2026-09-21', '10:30'), [slot]), false);
assert.equal(isAvailable(athensDate('2026-09-22', '09:30'), [slot]), false);
assert.equal(isAvailable(athensDate('2026-09-21', '09:30'), []), false);
assert.throws(() => athensDate('2026-03-29', '03:30'));
assert.deepEqual(athensParts(athensDate('2026-10-25', '03:30')), { date: '2026-10-25', time: '03:30' });
console.log('Availability validation, slot boundaries, weekdays and Athens timezone checks passed.');
